// lesson_11_castom_hooks/src/hooks/Api.tsx
import { useState, useEffect } from 'react';

type UseApiOptions = RequestInit;

type UseApiResult<T> = {
    data: T | null;
    loading: boolean;
    error: string | null;
};

function useApi<T>(url: string, options: UseApiOptions = {}): UseApiResult<T> {
    const [data, setData] = useState<T | null>(null);
    const [loading, setLoading] = useState<boolean>(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        fetch(url, options)
            .then(res => {
                if (!res.ok) {
                    throw new Error(`HTTP error! Status: ${res.status}`);
                }
                return res.json();
            })
            .then((data: T) => {
                setData(data);
            })
            .catch((err: Error) => {
                setError(err.message);
            }).finally(() => {
                setLoading(false);
            });
    }, [url, options]);

    return { data, loading, error };
}

export default useApi;

// lesson_18_vue/src/composables/Api.tsx
import { ref, watch, type Ref } from 'vue';

type UseApiOptions = RequestInit;

type UseApiResult<T> = {
  data: Ref<T | null>;
  loading: Ref<boolean>;
  error: Ref<string | null>;
  refresh: () => void;
};

function useApi<T>(url: string, options: UseApiOptions = {}): UseApiResult<T> {
  const data = ref<T | null>(null) as Ref<T | null>;
  const loading = ref<boolean>(false);
  const error = ref<string | null>(null);

  const fetchData = async () => {
    loading.value = true;
    error.value = null;
    try {
      //freeze 
      await new Promise(resolve => setTimeout(resolve, 300));

      const res = await fetch(url, options);

      if (!res.ok) {
        throw new Error(`HTTP error! Status: ${res.status}`);
      }

      const json = await res.json();
      data.value = json;
    } catch (err) {
      error.value = (err as Error).message;
    } finally {
      loading.value = false;
    }
  };

  watch(() => url, () => fetchData());
  watch(() => options, () => fetchData());

  return {
    data,
    loading,
    error,
    refresh: fetchData
  };
}

export default useApi;
